# ************************** SqlDBM: Snowflake *************************

version: 2

sources:
  - name: SOURCE
    quoting:
      database: false
      schema: false
      identifier: false
    database: DBT_DEMO_TEST_DEVELOP
    schema: LAKESNOWHOUSE

    tables:
      - name: Products
        description: This table contains details about the products that are reviewed by users. It includes product names, categories, and pricing information. The Products table is essential for product-based analysis, inventory management, and sales strategy formulation.
        columns:
          - name: ProductID
            description: Unique identifier of the product.
          - name: ProductName
            description: Name of the product.
          - name: Category
            description: Category of the product.
          - name: Price
            description: Price of the product.