
name: 'dbt_lake_snowhouse'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  dbt_lake_snowhouse:
    staging:
      +schema: staging
      +materialized: 'view'
    bronze:
      +schema: bronze
      +materialized: 'ephemeral'
    silver:
      +schema: silver
      +materialized: 'incremental'
    gold:
      +schema: gold
      +materialized: 'table'

